### ISSUE TITLE
No module named 'space'

### ISSUE THREAD

**Issue by liruiluo** [VITA-Group/DiffSES#1]
when I use :python main.py --task train --config configs/atari_spaceinvaders.yaml resume True device 'cuda:0'
then the following error happened:
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from engine.utils import get_config
  File "/home/l/Downloads/DiffSES/space/engine/utils.py", line 4, in <module>
    from space.config import cfg
ModuleNotFoundError: No module named 'space'

**Comment by farhanfuadabir** [comment]
Hi, 

I was trying to run the code as well and got a similar error message. Trace the error message for the lines with dependencies error. For example, here, check the file "/home/l/Downloads/DiffSES/space/engine/utils.py", line 4, and locate

`from space.config import cfg`

change it to:

`from config import cfg`

Then you will probably get more of such errors. Just change accordingly.

Hope it helps.

**Comment by liruiluo** [comment]
> 你好，
> 
> 我也试图运行代码并收到类似的错误消息。跟踪具有依赖项错误的行的错误消息。比如这里，查看文件“/home/l/Downloads/DiffSES/space/engine/utils.py”，第4行，定位
> 
> `from space.config import cfg`
> 
> 将其更改为：
> 
> `from config import cfg`
> 
> 然后你可能会得到更多这样的错误。只是相应地改变。
> 
> 希望能帮助到你。

Thanks！That works for me！
